const termsAndCons = [
  {
    Termstitle: "Booking Policy:",
    TermsContent:
      "A reservation fee is required to confirm the booking and secure the schedule.",
    AddedContent: "• Reservation Fee:",
  },
  {
    Termstitle: "Cancellation Policy:",
    TermsContent:
      "If the customer is not present at the scheduled reservation time, the fee is also non-refundable.",
    AddedContent: "• Cancellations are non-refundable.",
  },
  {
    Termstitle: "Repairs and Maintenance:",
    TermsContent:
      "VanGO will cover all costs related to van repairs and maintenance.",
  },
  {
    Termstitle: "Accidents and Damages:",
    TermsContent:
      "In the event of an accident, damages will be covered by the company’s insurance.",
    AddedContent: "• Passenger insurance will also be provided.",
  },
  {
    Termstitle: "Repairs and Maintenance:",
    TermsContent:
      "VanGO will cover all costs related to van repairs and maintenance.",
  },
  {
    TermsHeading: "Additional Terms :",
    Termstitle: "Driver Conduct:",
    TermsContent:
      "Drivers are expected to maintain professional conduct at all times.",
    AddedContent:
      "• Any inappropriate behavior may result in immediate termination of the service without a refund.",
    AddedContent1: "• Must not allow the customer to drive the rented vehicle",
    AddedContent2:
      "• Must not bring the vehicle without the consent or approval of the company and must not use the vehicle if the activity is not related to the customer’s trip",
  },
  {
    Termstitle: "Customer Conduct:",
    TermsContent:
      "For those under 18, a guardian is required when renting the van, as they cannot rent it alone.",
    AddedContent:
      "• Must return the rented van based on the contract agreement",
  },
  {
    Termstitle: "Passenger Responsibility:",
    TermsContent:
      "Passengers are responsible for their belongings. VanGO is not liable for lost or damaged personal items during the trip.",
  },
  {
    Termstitle: "Passenger Responsibility:",
    TermsContent:
      "Passengers are responsible for their belongings. VanGO is not liable for lost or damaged personal items during the trip.",
  },
  {
    Termstitle: "Schedule Changes:",
    TermsContent:
      "Any changes to the schedule must be communicated at least 24 hours in advance. Vango will do its best to accommodate changes, but cannot guarantee availability.",
  },
  {
    Termstitle: "Payment Terms:",
    TermsContent: "The remaining balance is due upon pick up or after service.",
    AddedContent:
      "• Payments can be made via cash through the drivers or via a bank account provided.",
  },
  {
    Termstitle: "Force Majeure:",
    TermsContent:
      "Vango is not liable for any delays or cancellations due to events beyond its control, such as natural disasters, traffic accidents, or other emergencies.",
  },
  {
    Termstitle: "Health and Safety:",
    TermsContent:
      "Passengers are required to follow all safety instructions provided by the driver.",
    AddedContent:
      "• Vango reserves the right to refuse service to anyone who is deemed to be a safety risk.",
  },
];

const cebuData = {
  CEBU: {
    municipality_list: {
      ALCANTARA: {
        barangay_list: [
          "CABADIANGAN",
          "CABIL-ISAN",
          "CANDABONG",
          "LAWAAN",
          "MANGA",
          "PALANAS",
          "POBLACION",
          "POLO",
          "SALAGMAYA",
        ],
      },
      ALCOY: {
        barangay_list: [
          "ATABAY",
          "DAAN-LUNGSOD",
          "GUIWANG",
          "NUG-AS",
          "PASOL",
          "POBLACION",
          "PUGALO",
          "SAN AGUSTIN",
        ],
      },
      ALEGRIA: {
        barangay_list: [
          "COMPOSTELA",
          "GUADALUPE",
          "LEGASPI",
          "LEPANTO",
          "MADRIDEJOS",
          "MONTPELLER",
          "POBLACION",
          "SANTA FILOMENA",
          "VALENCIA",
        ],
      },
      ALOGUINSAN: {
        barangay_list: [
          "ANGILAN",
          "BOJO",
          "BONBON",
          "ESPERANZA",
          "KANDINGAN",
          "KANTABOGON",
          "KAWASAN",
          "OLANGO",
          "POBLACION",
          "PUNAY",
          "ROSARIO",
          "SAKSAK",
          "TAMPA-AN",
          "TOYOKON",
          "ZARAGOSA",
        ],
      },
      ARGAO: {
        barangay_list: [
          "ALAMBIJUD",
          "ANAJAO",
          "APO",
          "BALAAS",
          "BALISONG",
          "BINLOD",
          "BOGO",
          "BUG-OT",
          "BULASA",
          "BUTONG",
          "CALAGASAN",
          "CANBANTUG",
          "CANBANUA",
          "CANSUJE",
          "CAPIO-AN",
          "CASAY",
          "CATANG",
          "COLAWIN",
          "CONALUM",
          "GUIWANON",
          "GUTLANG",
          "JAMPANG",
          "JOMGAO",
          "LAMACAN",
          "LANGTAD",
          "LANGUB",
          "LAPAY",
          "LENGIGON",
          "LINUT-OD",
          "MABASA",
          "MANDILIKIT",
          "MOMPELLER",
          "PANADTARAN",
          "POBLACION",
          "SUA",
          "SUMAGUAN",
          "TABAYAG",
          "TALAGA",
          "TALAYTAY",
          "TALO-OT",
          "TIGUIB",
          "TULANG",
          "TULIC",
          "UBAUB",
          "USMAD",
        ],
      },
      ASTURIAS: {
        barangay_list: [
          "AGBANGA",
          "AGTUGOP",
          "BAGO",
          "BAIRAN",
          "BANBAN",
          "BAYE",
          "BOG-O",
          "KALUANGAN",
          "LANAO",
          "LANGUB",
          "LOOC NORTE",
          "LUNAS",
          "MAGCALAPE",
          "MANGUIAO",
          "NEW BAGO",
          "OWAK",
          "POBLACION",
          "SAKSAK",
          "SAN ISIDRO",
          "SAN ROQUE",
          "SANTA LUCIA",
          "SANTA RITA",
          "TAG-AMAKAN",
          "TAGBUBONGA",
          "TUBIGAGMANOK",
          "TUBOD",
          "UBOGON",
        ],
      },
      BADIAN: {
        barangay_list: [
          "ALAWIJAO",
          "BALHAAN",
          "BANHIGAN",
          "BASAK",
          "BASIAO",
          "BATO",
          "BUGAS",
          "CALANGCANG",
          "CANDIIS",
          "DAGATAN",
          "DOBDOB",
          "GINABLAN",
          "LAMBUG",
          "MALABAGO",
          "MALHIAO",
          "MANDUYONG",
          "MATUTINAO",
          "PATONG",
          "POBLACION",
          "SANLAGAN",
          "SANTICON",
          "SOHOTON",
          "SULSUGAN",
          "TALAYONG",
          "TAYTAY",
          "TIGBAO",
          "TIGUIB",
          "TUBOD",
          "ZARAGOSA",
        ],
      },
      BALAMBAN: {
        barangay_list: [
          "ABUCAYAN",
          "ALIWANAY",
          "ARPILI",
          "BALIWAGAN (POB.)",
          "BAYONG",
          "BIASONG",
          "BUANOY",
          "CABAGDALAN",
          "CABASIANGAN",
          "CAMBUHAWE",
          "CANSOMOROY",
          "CANTIBAS",
          "CANTUOD",
          "DUANGAN",
          "GAAS",
          "GINATILAN",
          "HINGATMONAN",
          "LAMESA",
          "LIKI",
          "LUCA",
          "MATUN-OG",
          "NANGKA",
          "PONDOL",
          "PRENZA",
          "SANTA CRUZ-SANTO NIÑO (POB.)",
          "SINGSING",
          "SUNOG",
          "VITO",
        ],
      },
      BANTAYAN: {
        barangay_list: [
          "ATOP-ATOP",
          "BAIGAD",
          "BANTIGUE (POB.)",
          "BAOD",
          "BINAOBAO (POB.)",
          "BOTIGUES",
          "DOONG",
          "GUIWANON",
          "HILOTONGAN",
          "KABAC",
          "KABANGBANG",
          "KAMPINGGANON",
          "KANGKAIBE",
          "LIPAYRAN",
          "LUYONGBAYBAY",
          "MOJON",
          "OBO-OB",
          "PATAO",
          "PUTIAN",
          "SILLON",
          "SUBA (POB.)",
          "SULANGAN",
          "SUNGKO",
          "TAMIAO",
          "TICAD (POB.)",
        ],
      },
      BARILI: {
        barangay_list: [
          "AZUCENA",
          "BAGAKAY",
          "BALAO",
          "BOLOCBOLOC",
          "BUDBUD",
          "BUGTONG KAWAYAN",
          "CABCABAN",
          "CAGAY",
          "CAMPANGGA",
          "CANDUGAY",
          "DAKIT",
          "GILOCTOG",
          "GIWANON",
          "GUIBUANGAN",
          "GUNTING",
          "HILASGASAN",
          "JAPITAN",
          "KALUBIHAN",
          "KANGDAMPAS",
          "LUHOD",
          "LUPO",
          "LUYO",
          "MAGHANOY",
          "MAIGANG",
          "MALOLOS",
          "MANTALONGON",
          "MANTAYUPAN",
          "MAYANA",
          "MINOLOS",
          "NABUNTURAN",
          "NASIPIT",
          "PANCIL",
          "PANGPANG",
          "PARIL",
          "PATUPAT",
          "POBLACION",
          "SAN RAFAEL",
          "SANTA ANA",
          "SAYAW",
          "TAL-OT",
          "TUBOD",
          "VITO",
        ],
      },
      "BOGO CITY": {
        barangay_list: [
          "ANONANG NORTE",
          "ANONANG SUR",
          "BANBAN",
          "BINABAG",
          "BUNGTOD (POB.)",
          "CARBON (POB.)",
          "CAYANG",
          "COGON (POB.)",
          "DAKIT",
          "DON PEDRO RODRIGUEZ",
          "GAIRAN",
          "GUADALUPE",
          "LA PAZ",
          "LA PURISIMA CONCEPCION (POB.)",
          "LIBERTAD",
          "LOURDES (POB.)",
          "MALINGIN",
          "MARANGOG",
          "NAILON",
          "ODLOT",
          "PANDAN (PANDAN HEIGHTS)",
          "POLAMBATO",
          "SAMBAG (POB.)",
          "SAN VICENTE (POB.)",
          "SANTO NIÑO",
          "SANTO ROSARIO (POB.)",
          "SIOCON",
          "SUDLONON",
          "TAYTAYAN",
        ],
      },
      BOLJOON: {
        barangay_list: [
          "ARBOR",
          "BACLAYAN",
          "EL PARDO",
          "GRANADA",
          "LOWER BECERRIL",
          "LUNOP",
          "NANGKA",
          "POBLACION",
          "SAN ANTONIO",
          "SOUTH GRANADA",
          "UPPER BECERRIL",
        ],
      },
      BORBON: {
        barangay_list: [
          "BAGACAY",
          "BILI",
          "BINGAY",
          "BONGDO",
          "BONGDO GUA",
          "BONGOYAN",
          "CADARUHAN",
          "CAJEL",
          "CAMPUSONG",
          "CLAVERA",
          "DON GREGORIO ANTIGUA (TAYTAYAN)",
          "LAAW",
          "LUGO",
          "MANAGASE",
          "POBLACION",
          "SAGAY",
          "SAN JOSE",
          "TABUNAN",
          "TAGNUCAN",
        ],
      },
      "CARCAR CITY": {
        barangay_list: [
          "BOLINAWAN",
          "BUENAVISTA",
          "CALIDNGAN",
          "CAN-ASUJAN",
          "GUADALUPE",
          "LIBURON",
          "NAPO",
          "OCANA",
          "PERRELOS",
          "POBLACION I",
          "POBLACION II",
          "POBLACION III",
          "TUYOM",
          "VALENCIA",
          "VALLADOLID",
        ],
      },
      CARMEN: {
        barangay_list: [
          "BARING",
          "CANTIPAY",
          "CANTUKONG",
          "CANTUMOG",
          "CAURASAN",
          "COGON EAST",
          "COGON WEST",
          "CORTE",
          "DAWIS NORTE",
          "DAWIS SUR",
          "HAGNAYA",
          "IPIL",
          "LANIPGA",
          "LIBORON",
          "LOWER NATIMAO-AN",
          "LUYANG",
          "POBLACION",
          "PUENTE",
          "SAC-ON",
          "TRIUMFO",
          "UPPER NATIMAO-AN",
        ],
      },
      CATMON: {
        barangay_list: [
          "AGSUWAO",
          "AMANCION",
          "ANAPOG",
          "BACTAS",
          "BASAK",
          "BINONGKALAN",
          "BONGYAS",
          "CABUNGAAN",
          "CAMBANGKAYA",
          "CAN-IBUANG",
          "CATMONDAAN",
          "CORAZON (POB.)",
          "DUYAN",
          "FLORES (POB.)",
          "GINABUCAN",
          "MACAAS",
          "PANALIPAN",
          "SAN JOSE POB. (CATADMAN)",
          "TABILI",
          "TINABYONAN",
        ],
      },
      "CEBU CITY": {
        barangay_list: [
          "ADLAON",
          "AGSUNGOT",
          "APAS",
          "BABAG",
          "BACAYAN",
          "BANILAD",
          "BASAK PARDO",
          "BASAK SAN NICOLAS",
          "BINALIW",
          "BONBON",
          "BUDLA-AN (POB.)",
          "BUHISAN",
          "BULACAO",
          "BUOT-TAUP PARDO",
          "BUSAY (POB.)",
          "CALAMBA",
          "CAMBINOCOT",
          "CAMPUTHAW (POB.)",
          "CAPITOL SITE (POB.)",
          "CARRETA",
          "CENTRAL (POB.)",
          "COGON PARDO",
          "COGON RAMOS (POB.)",
          "DAY-AS",
          "DULJO (POB.)",
          "ERMITA (POB.)",
          "GUADALUPE",
          "GUBA",
          "HIPPODROMO",
          "INAYAWAN",
          "KALUBIHAN (POB.)",
          "KALUNASAN",
          "KAMAGAYAN (POB.)",
          "KASAMBAGAN",
          "KINASANG-AN PARDO",
          "LABANGON",
          "LAHUG (POB.)",
          "LOREGA (LOREGA SAN MIGUEL)",
          "LUSARAN",
          "LUZ",
          "MABINI",
          "MABOLO",
          "MALUBOG",
          "MAMBALING",
          "PAHINA CENTRAL (POB.)",
          "PAHINA SAN NICOLAS",
          "PAMUTAN",
          "PARDO (POB.)",
          "PARI-AN",
          "PARIL",
          "PASIL",
          "PIT-OS",
          "PULANGBATO",
          "PUNG-OL-SIBUGAY",
          "PUNTA PRINCESA",
          "QUIOT PARDO",
          "SAMBAG I (POB.)",
          "SAMBAG II (POB.)",
          "SAN ANTONIO (POB.)",
          "SAN JOSE",
          "SAN NICOLAS CENTRAL",
          "SAN ROQUE (CIUDAD)",
          "SANTA CRUZ (POB.)",
          "SAPANGDAKU",
          "SAWANG CALERO (POB.)",
          "SINSIN",
          "SIRAO",
          "SUBA POB. (SUBA SAN NICOLAS)",
          "SUDLON I",
          "SUDLON II",
          "T. PADILLA",
          "TABUNAN",
          "TAGBAO",
          "TALAMBAN",
          "TAPTAP",
          "TEJERO (VILLA GONZALO)",
          "TINAGO",
          "TISA",
          "TO-ONG PARDO",
          "ZAPATERA",
        ],
      },
      COMPOSTELA: {
        barangay_list: [
          "BAGALNGA",
          "BASAK",
          "BULUANG",
          "CABADIANGAN",
          "CAMBAYOG",
          "CANAMUCAN",
          "COGON",
          "DAPDAP",
          "ESTACA",
          "LUPA",
          "MAGAY",
          "MULAO",
          "PANANGBAN",
          "POBLACION",
          "TAG-UBE",
          "TAMIAO",
          "TUBIGAN",
        ],
      },
      CONSOLACION: {
        barangay_list: [
          "CABANGAHAN",
          "CANSAGA",
          "CASILI",
          "DANGLAG",
          "GARING",
          "JUGAN",
          "LAMAC",
          "LANIPGA",
          "NANGKA",
          "PANAS",
          "PANOYPOY",
          "PITOGO",
          "POBLACION OCCIDENTAL",
          "POBLACION ORIENTAL",
          "POLOG",
          "PULPOGAN",
          "SACSAC",
          "TAYUD",
          "TILHAONG",
          "TOLOTOLO",
          "TUGBONGAN",
        ],
      },
      CORDOBA: {
        barangay_list: [
          "ALEGRIA",
          "BANGBANG",
          "BUAGSONG",
          "CATARMAN",
          "COGON",
          "DAPITAN",
          "DAY-AS",
          "GABI",
          "GILUTONGAN",
          "IBABAO",
          "PILIPOG",
          "POBLACION",
          "SAN MIGUEL",
        ],
      },
      DAANBANTAYAN: {
        barangay_list: [
          "AGUHO",
          "BAGAY",
          "BAKHAWAN",
          "BATERIA",
          "BITOON",
          "CALAPE",
          "CARNAZA",
          "DALINGDING",
          "LANAO",
          "LOGON",
          "MALBAGO",
          "MALINGIN",
          "MAYA",
          "PAJO",
          "PAYPAY",
          "POBLACION",
          "TALISAY",
          "TAPILON",
          "TINUBDAN",
          "TOMINJAO",
        ],
      },
      DALAGUETE: {
        barangay_list: [
          "ABLAYAN",
          "BABAYONGAN",
          "BALUD",
          "BANHIGAN",
          "BULAK",
          "CALERIOHAN",
          "CALIONGAN",
          "CASAY",
          "CATOLOHAN",
          "CAWAYAN",
          "CONSOLACION",
          "CORO",
          "DUGYAN",
          "DUMALAN",
          "JOLOMAYNON",
          "LANAO",
          "LANGKAS",
          "LUMBANG",
          "MALONES",
          "MALORAY",
          "MANANGGAL",
          "MANLAPAY",
          "MANTALONGON",
          "NALHUB",
          "OBO",
          "OBONG",
          "PANAS",
          "POBLACION",
          "SACSAC",
          "SALUG",
          "TABON",
          "TAPUN",
          "TUBA",
        ],
      },
      "DANAO CITY": {
        barangay_list: [
          "BALIANG",
          "BAYABAS",
          "BINALIW",
          "CABUNGAHAN",
          "CAGAT-LAMAC",
          "CAHUMAYAN",
          "CAMBANAY",
          "CAMBUBHO",
          "COGON-CRUZ",
          "DANASAN",
          "DUNGGA",
          "DUNGGOAN",
          "GUINACOT",
          "GUINSAY",
          "IBO",
          "LANGOSIG",
          "LAWAAN",
          "LICOS",
          "LOOC",
          "MAGTAGOBTOB",
          "MALAPOC",
          "MANLAYAG",
          "MANTIJA",
          "MASABA",
          "MASLOG",
          "NANGKA",
          "OGUIS",
          "PILI",
          "POBLACION",
          "QUISOL",
          "SABANG",
          "SACSAC",
          "SANDAYONG NORTE",
          "SANDAYONG SUR",
          "SANTA ROSA",
          "SANTICAN",
          "SIBACAN",
          "SUBA",
          "TABOC",
          "TAYTAY",
          "TOGONON",
          "TUBURAN SUR",
        ],
      },
      DUMANJUG: {
        barangay_list: [
          "BALAYGTIKI",
          "BITOON",
          "BULAK",
          "BULLOGAN",
          "CALABOON",
          "CAMBOANG",
          "CANDABONG",
          "COGON",
          "COTCOTON",
          "DOLDOL",
          "ILAYA (POB.)",
          "KABALAASNAN",
          "KABATBATAN",
          "KAMBANOG",
          "KANG-ACTOL",
          "KANGHALO",
          "KANGHUMAOD",
          "KANGUHA",
          "KANTANGKAS",
          "KANYUKO",
          "KOLABTINGON",
          "LAMAK",
          "LAWAAN",
          "LIONG",
          "MANLAPAY",
          "MASA",
          "MATALAO",
          "PACULOB",
          "PANLAAN",
          "PAWA",
          "POBLACION CENTRAL",
          "POBLACION LOOC",
          "POBLACION SIMA",
          "TANGIL",
          "TAPON",
          "TUBOD-BITOON",
          "TUBOD-DUGOAN",
        ],
      },
      GINATILAN: {
        barangay_list: [
          "ANAO",
          "CAGSING",
          "CALABAWAN",
          "CAMBAGTE",
          "CAMPISONG",
          "CANORONG",
          "GUIWANON",
          "LOOC",
          "MALATBO",
          "MANGACO",
          "PALANAS",
          "POBLACION",
          "SALAMANCA",
          "SAN ROQUE",
        ],
      },
      "LAPU-LAPU CITY (OPON)": {
        barangay_list: [
          "AGUS",
          "BABAG",
          "BANKAL",
          "BARING",
          "BASAK",
          "BUAYA",
          "CALAWISAN",
          "CANJULAO",
          "CAUBIAN",
          "CAW-OY",
          "CAWHAGAN",
          "GUN-OB",
          "IBO",
          "LOOC",
          "MACTAN",
          "MARIGONDON",
          "PAJAC",
          "PAJO",
          "PANGAN-AN",
          "POBLACION",
          "PUNTA ENGAÑO",
          "PUSOK",
          "SABANG",
          "SAN VICENTE",
          "SANTA ROSA",
          "SUBABASBAS",
          "TALIMA",
          "TINGO",
          "TUNGASAN",
        ],
      },
      LILOAN: {
        barangay_list: [
          "CABADIANGAN",
          "CALERO",
          "CATARMAN",
          "COTCOT",
          "JUBAY",
          "LATABAN",
          "MULAO",
          "POBLACION",
          "SAN ROQUE",
          "SAN VICENTE",
          "SANTA CRUZ",
          "TABLA",
          "TAYUD",
          "YATI",
        ],
      },
      MADRIDEJOS: {
        barangay_list: [
          "BUNAKAN",
          "KANGWAYAN",
          "KAONGKOD",
          "KODIA",
          "MAALAT",
          "MALBAGO",
          "MANCILANG",
          "PILI",
          "POBLACION",
          "SAN AGUSTIN",
          "TABAGAK",
          "TALANGNAN",
          "TARONG",
          "TUGAS",
        ],
      },
      MALABUYOC: {
        barangay_list: [
          "ARMEÑA (CANSILONGAN)",
          "BARANGAY I (POB.)",
          "BARANGAY II (POB.)",
          "CERDEÑA (ANSAN)",
          "LABRADOR (BULOD)",
          "LOMBO",
          "LOOC",
          "MAHANLUD",
          "MINDANAO (PAJO)",
          "MONTAÑEZA (INAMLANG)",
          "SALMERON (BULAK)",
          "SANTO NIÑO",
          "SORSOGON (BALIMAYA)",
          "TOLOSA (CALATAGAN)",
        ],
      },
      "MANDAUE CITY": {
        barangay_list: [
          "ALANG-ALANG",
          "BAKILID",
          "BANILAD",
          "BASAK",
          "CABANCALAN",
          "CAMBARO",
          "CANDUMAN",
          "CASILI",
          "CASUNTINGAN",
          "CENTRO (POB.)",
          "CUBACUB",
          "GUIZO",
          "IBABAO-ESTANCIA",
          "JAGOBIAO",
          "LABOGON",
          "LOOC",
          "MAGUIKAY",
          "MANTUYONG",
          "OPAO",
          "PAGSABUNGAN",
          "PAKNA-AN",
          "SUBANGDAKU",
          "TABOK",
          "TAWASON",
          "TINGUB",
          "TIPOLO",
          "UMAPAD",
        ],
      },
      MEDELLIN: {
        barangay_list: [
          "ANTIPOLO",
          "CANHABAGAT",
          "CAPUTATAN NORTE",
          "CAPUTATAN SUR",
          "CURVA",
          "DAANLUNGSOD",
          "DALINGDING SUR",
          "DAYHAGON",
          "DON VIRGILIO GONZALES",
          "GIBITNGIL",
          "KAWIT",
          "LAMINTAK NORTE",
          "LAMINTAK SUR",
          "LUY-A",
          "MAHARUHAY",
          "MAHAWAK",
          "PANUGNAWAN",
          "POBLACION",
          "TINDOG",
        ],
      },
      MINGLANILLA: {
        barangay_list: [
          "CADULAWAN",
          "CALAJO-AN",
          "CAMP 7",
          "CAMP 8",
          "CUANOS",
          "GUINDARUHAN",
          "LINAO",
          "MANDUANG",
          "PAKIGNE",
          "POBLACION WARD I",
          "POBLACION WARD II",
          "POBLACION WARD III",
          "POBLACION WARD IV",
          "TUBOD",
          "TULAY",
          "TUNGHAAN",
          "TUNGKIL",
          "TUNGKOP",
          "VITO",
        ],
      },
      MOALBOAL: {
        barangay_list: [
          "AGBALANGA",
          "BALA",
          "BALABAGON",
          "BASDIOT",
          "BATADBATAD",
          "BUGHO",
          "BUGUIL",
          "BUSAY",
          "LANAO",
          "POBLACION EAST",
          "POBLACION WEST",
          "SAAVEDRA",
          "TOMONOY",
          "TUBLE",
          "TUNGA",
        ],
      },
      "NAGA CITY": {
        barangay_list: [
          "ALFACO",
          "BAIRAN",
          "BALIRONG",
          "CABUNGAHAN",
          "CANTAO-AN",
          "CENTRAL POBLACION",
          "COGON",
          "COLON",
          "EAST POBLACION",
          "INAYAGAN",
          "INOBURAN",
          "JAGUIMIT",
          "LANAS",
          "LANGTAD",
          "LUTAC",
          "MAINIT",
          "MAYANA",
          "NAALAD",
          "NORTH POBLACION",
          "PANGDAN",
          "PATAG",
          "SOUTH POBLACION",
          "TAGJAGUIMIT",
          "TANGKE",
          "TINAAN",
          "TUYAN",
          "ULING",
          "WEST POBLACION",
        ],
      },
      OSLOB: {
        barangay_list: [
          "ALO",
          "BANGCOGON",
          "BONBON",
          "CALUMPANG",
          "CAN-UKBAN",
          "CANANGCA-AN",
          "CANSALO-AY",
          "CAÑANG",
          "DAANLUNGSOD",
          "GAWI",
          "HAGDAN",
          "LAGUNDE",
          "LOOC",
          "LUKA",
          "MAINIT",
          "MANLUM",
          "NUEVA CACERES",
          "POBLACION",
          "PUNGTOD",
          "TAN-AWAN",
          "TUMALOG",
        ],
      },
      PILAR: {
        barangay_list: [
          "BIASONG",
          "CAWIT",
          "DAPDAP",
          "ESPERANZA",
          "IMELDA",
          "LANAO",
          "LOWER POBLACION",
          "MOABOG",
          "MONTSERRAT",
          "SAN ISIDRO",
          "SAN JUAN",
          "UPPER POBLACION",
          "VILLAHERMOSA",
        ],
      },
      PINAMUNGAHAN: {
        barangay_list: [
          "ANISLAG",
          "ANOPOG",
          "BINABAG",
          "BUHINGTUBIG",
          "BUSAY",
          "BUTONG",
          "CABIANGON",
          "CAMUGAO",
          "DUANGAN",
          "GUIMBAWIAN",
          "LAMAC",
          "LUT-OD",
          "MANGOTO",
          "OPAO",
          "PANDACAN",
          "POBLACION",
          "PUNOD",
          "RIZAL",
          "SACSAC",
          "SAMBAGON",
          "SIBAGO",
          "TAJAO",
          "TANGUB",
          "TANIBAG",
          "TUPAS",
          "TUTAY",
        ],
      },
      PORO: {
        barangay_list: [
          "ADELA",
          "ALTAVISTA",
          "CAGCAGAN",
          "CANSABUSAB",
          "DAAN PAZ",
          "EASTERN POBLACION",
          "ESPERANZA",
          "LIBERTAD",
          "MABINI",
          "MERCEDES",
          "PAGSA",
          "PAZ",
          "RIZAL",
          "SAN JOSE",
          "SANTA RITA",
          "TEGUIS",
          "WESTERN POBLACION",
        ],
      },
      RONDA: {
        barangay_list: [
          "BUTONG",
          "CAN-ABUHON",
          "CANDULING",
          "CANSALONOY",
          "CANSAYAHON",
          "ILAYA",
          "LANGIN",
          "LIBO-O",
          "MALALAY",
          "PALANAS",
          "POBLACION",
          "SANTA CRUZ",
          "TUPAS",
          "VIVE",
        ],
      },
      SAMBOAN: {
        barangay_list: [
          "BASAK",
          "BONBON",
          "BULANGSURAN",
          "CALATAGAN",
          "CAMBIGONG",
          "CAMBUROY",
          "CANORONG",
          "COLASE",
          "DALAHIKAN",
          "JUMANGPAS",
          "MONTEVERDE",
          "POBLACION",
          "SAN SEBASTIAN",
          "SUBA",
          "TANGBO",
        ],
      },
      "SAN FERNANDO": {
        barangay_list: [
          "BALUD",
          "BALUNGAG",
          "BASAK",
          "BUGHO",
          "CABATBATAN",
          "GREENHILLS",
          "ILAYA",
          "LANTAWAN",
          "LIBURON",
          "MAGSICO",
          "PANADTARAN",
          "PITALO",
          "POBLACION NORTH",
          "POBLACION SOUTH",
          "SAN ISIDRO",
          "SANGAT",
          "TABIONAN",
          "TANANAS",
          "TINUBDAN",
          "TONGGO",
          "TUBOD",
        ],
      },
      "SAN FRANCISCO": {
        barangay_list: [
          "CABUNGA-AN",
          "CAMPO",
          "CONSUELO",
          "ESPERANZA",
          "HIMENSULAN",
          "MONTEALEGRE",
          "NORTHERN POBLACION",
          "SAN ISIDRO",
          "SANTA CRUZ",
          "SANTIAGO",
          "SONOG",
          "SOUTHERN POBLACION",
          "UNIDOS",
          "UNION",
          "WESTERN POBLACION",
        ],
      },
      "SAN REMIGIO": {
        barangay_list: [
          "ANAPOG",
          "ARGAWANON",
          "BAGTIC",
          "BANCASAN",
          "BATAD",
          "BUSOGON",
          "CALAMBUA",
          "CANAGAHAN",
          "DAPDAP",
          "GAWAYGAWAY",
          "HAGNAYA",
          "KAYAM",
          "KINAWAHAN",
          "LAMBUSAN",
          "LAWIS",
          "LIBAONG",
          "LOOC",
          "LUYANG",
          "MANO",
          "POBLACION",
          "PUNTA",
          "SAB-A",
          "SAN MIGUEL",
          "TACUP",
          "TAMBONGON",
          "TO-ONG",
          "VICTORIA",
        ],
      },
      "SANTA FE": {
        barangay_list: [
          "BALIDBID",
          "HAGDAN",
          "HILANTAGAAN",
          "KINATARKAN",
          "LANGUB",
          "MARICABAN",
          "OKOY",
          "POBLACION",
          "POOC",
          "TALISAY",
        ],
      },
      SANTANDER: {
        barangay_list: [
          "BUNLAN",
          "CABUTONGAN",
          "CANDAMIANG",
          "CANLUMACAD",
          "LILOAN",
          "LIP-TONG",
          "LOOC",
          "PASIL",
          "POBLACION",
          "TALISAY",
        ],
      },
      SIBONGA: {
        barangay_list: [
          "ABUGON",
          "BAE",
          "BAGACAY",
          "BAHAY",
          "BANLOT",
          "BASAK",
          "BATO",
          "CAGAY",
          "CAN-AGA",
          "CANDAGUIT",
          "CANTOLAROY",
          "DUGOAN",
          "GUIMBANGCO-AN",
          "LAMACAN",
          "LIBO",
          "LINDOGON",
          "MAGCAGONG",
          "MANATAD",
          "MANGYAN",
          "PAPAN",
          "POBLACION",
          "SABANG",
          "SAYAO",
          "SIMALA",
          "TUBOD",
        ],
      },
      SOGOD: {
        barangay_list: [
          "AMPONGOL",
          "BAGAKAY",
          "BAGATAYAM",
          "BAWO",
          "CABALAWAN",
          "CABANGAHAN",
          "CALUMBOYAN",
          "DAKIT",
          "DAMOLOG",
          "IBABAO",
          "LIKI",
          "LUBO",
          "MOHON",
          "NAHUS-AN",
          "PANSOY",
          "POBLACION",
          "TABUNOK",
          "TAKAY",
        ],
      },
      TABOGON: {
        barangay_list: [
          "ALANG-ALANG",
          "CADUAWAN",
          "CAMOBOAN",
          "CANAOCANAO",
          "COMBADO",
          "DAANTABOGON",
          "ILIHAN",
          "KAL-ANAN",
          "LABANGON",
          "LIBJO",
          "LOONG",
          "MABULI",
          "MANAGASE",
          "MANLAGTANG",
          "MASLOG",
          "MUABOG",
          "PIO",
          "POBLACION",
          "SALAG",
          "SAMBAG",
          "SAN ISIDRO",
          "SAN VICENTE",
          "SOMOSA",
          "TABA-AO",
          "TAPUL",
        ],
      },
      TABUELAN: {
        barangay_list: [
          "BONGON",
          "DALID",
          "KANLIM-AO",
          "KANLUHANGON",
          "KANTUBAON",
          "MABUNAO",
          "MARAVILLA",
          "OLIVO",
          "POBLACION",
          "TABUNOK",
          "TIGBAWAN",
          "VILLAHERMOSA",
        ],
      },
      "TALISAY CITY": {
        barangay_list: [
          "BIASONG",
          "BULACAO",
          "CADULAWAN",
          "CAMP IV",
          "CANSOJONG",
          "DUMLOG",
          "JACLUPAN",
          "LAGTANG",
          "LAWAAN I",
          "LAWAAN II",
          "LAWAAN III",
          "LINAO",
          "MAGHAWAY",
          "MANIPIS",
          "MOHON",
          "POBLACION",
          "POOC",
          "SAN ISIDRO",
          "SAN ROQUE",
          "TABUNOC",
          "TANGKE",
          "TAPUL",
        ],
      },
      "TOLEDO CITY": {
        barangay_list: [
          "AWIHAO",
          "BAGAKAY",
          "BATO",
          "BIGA",
          "BULONGAN",
          "BUNGA",
          "CABITOONAN",
          "CALONGCALONG",
          "CAMBANG-UG",
          "CAMP 8",
          "CANLUMAMPAO",
          "CANTABACO",
          "CAPITAN CLAUDIO",
          "CARMEN",
          "DAANGLUNGSOD",
          "DON ANDRES SORIANO (LUTOPAN)",
          "DUMLOG",
          "GEN. CLIMACO (MALUBOG)",
          "IBO",
          "ILIHAN",
          "JUAN CLIMACO, SR. (MAGDUGO)",
          "LANDAHAN",
          "LOAY",
          "LURAY II",
          "MATAB-ANG",
          "MEDIA ONCE",
          "PANGAMIHAN",
          "POBLACION",
          "POOG",
          "PUTINGBATO",
          "SAGAY",
          "SAM-ANG",
          "SANGI",
          "SANTO NIÑO (MAINGGIT)",
          "SUBAYON",
          "TALAVERA",
          "TUBOD",
          "TUNGKAY",
        ],
      },
      TUBURAN: {
        barangay_list: [
          "ALEGRIA",
          "AMATUGAN",
          "ANTIPOLO",
          "APALAN",
          "BAGASAWE",
          "BAKYAWAN",
          "BANGKITO",
          "BARANGAY I (POB.)",
          "BARANGAY II (POB.)",
          "BARANGAY III (POB.)",
          "BARANGAY IV (POB.)",
          "BARANGAY V (POB.)",
          "BARANGAY VI (POB.)",
          "BARANGAY VII (POB.)",
          "BARANGAY VIII (POB.)",
          "BULWANG",
          "CARIDAD",
          "CARMELO",
          "COGON",
          "COLONIA",
          "DAAN LUNGSOD",
          "FORTALIZA",
          "GA-ANG",
          "GIMAMA-A",
          "JAGBUAYA",
          "KABANGKALAN",
          "KABKABAN",
          "KAGBA-O",
          "KALANGAHAN",
          "KAMANSI",
          "KAMPOOT",
          "KAN-AN",
          "KANLUNSING",
          "KANSI",
          "KAORASAN",
          "LIBO",
          "LUSONG",
          "MACUPA",
          "MAG-ALWA",
          "MAG-ANTOY",
          "MAG-ATUBANG",
          "MAGHAN-AY",
          "MANGGA",
          "MARMOL",
          "MOLOBOLO",
          "MONTEALEGRE",
          "PUTAT",
          "SAN JUAN",
          "SANDAYONG",
          "SANTO NIÑO",
          "SIOTES",
          "SUMON",
          "TOMINJAO",
          "TOMUGPA",
        ],
      },
      TUDELA: {
        barangay_list: [
          "BUENAVISTA",
          "CALMANTE",
          "DAAN SECANTE",
          "GENERAL",
          "MCARTHUR",
          "NORTHERN POBLACION",
          "PUERTOBELLO",
          "SANTANDER",
          "SECANTE BAG-O",
          "SOUTHERN POBLACION",
          "VILLAHERMOSA",
        ],
      },
    },
  },
};

const serviceCardData = [
  {
    image: "/icon/service-company.svg",
    title: "Company Service",
    description:
      "Our company provides a suite of tailored solutions to meet your diverse needs. From personalized private tours to seamless airport transfers, heartfelt Balik Probinsya assistance, stress-free hotel pickups and drop-offs, and comprehensive wedding services, we're dedicated to making every journey memorable and every occasion extraordinary.",
  },
  {
    image: "/icon/service-tour.svg",
    title: "Private Tours",
    description:
      "Embark on a personalized adventure with our private tours. Discover the beauty of your chosen destinations with knowledgeable guides who cater to your interests and preferences, ensuring an unforgettable experience every step of the way.",
  },
  {
    image: "/icon/service-transfer.svg",
    title: "Airport Transfer",
    description:
      "Start or end your travels with ease with our reliable airport transfer service. Enjoy punctual pickups and drop-offs, allowing you to travel stress-free and focus on enjoying your journey to or from the airport.",
  },
  {
    image: "/icon/service-travel-luggage.svg",
    title: "Balik Probinsya",
    description:
      "Let us assist you in reconnecting with your roots with our Balik Probinsya service. Whether you're returning to your hometown or exploring a new province, we provide seamless support to ensure a smooth transition and a warm welcome back home.",
  },
  {
    image: "/icon/service-outing.svg",
    title: "Outing",
    description:
      "Whether it's a day trip, a group adventure, or a special event, we make sure your outing is comfortable and stress-free. Travel together, create lasting memories, and enjoy every moment of the journey.",
  },
  {
    image: "/icon/service-wedding.svg",
    title: "Wedding Service",
    description:
      "Turn your dream wedding into reality with our comprehensive wedding services. From elegant transportation for the bridal party to meticulous planning and coordination, we're here to make your special day unforgettable and stress-free.",
  },
  {
    image: "/icon/service-hotel-transfer.svg",
    title: "Hotel Transfer",
    description:
      "Make your hotel stays hassle-free with our convenient pickup and drop-off service. Arrive and depart in comfort and style, with our reliable transportation ensuring a seamless transition to or from your accommodation.",
  },
  {
    image: "/icon/service-family-trips.svg",
    title: "Family Trips",
    description:
      "Make your family trips more enjoyable with spacious and comfortable transportation. Travel together with ease, creating unforgettable memories while we take care of the journey.",
  },
];

const chooseUsCard = [
  {
    id: 1,
    title: "Negotiate Rates",
    description:
      "Flexible pricing options that can be adjusted or discussed to accommodate individual needs and circumstances.",
    image: "/icon/icon-negotiate.svg",
  },
  {
    id: 2,
    title: "Professional and Reliable Driver Rates",
    description:
      "A skilled and trustworthy driver who ensures a safe and reliable travel experience for passengers.",
    image: "/icon/icon-driver.svg",
  },
  {
    id: 3,
    title: " Comfy , Safe, Free Hassle Travel",
    description:
      "Providing passengers with a comfortable and secure journey, free from any unnecessary difficulties or inconveniences.",
    image: "/icon/icon-comfy.svg",
  },
  {
    id: 4,
    title: "Passenger Insurance",
    description:
      "Flexible pricing options that can be adjusted or discussed to accommodate individual needs and circumstances.",
    image: "/icon/icon-insurance.svg",
  },
  {
    id: 5,
    title: "First Aid kit",
    description:
      "Offers Insurance  protecting passengers in case of injury or loss during travel.",
    image: "/icon/icon-first-aid.svg",
  },
  {
    id: 6,
    title: "Fire Extinguisher",
    description:
      "Safety device used to extinguish small fires and prevent their spread, providing an added layer of safety during travel.",
    image: "/icon/icon-fire-extinguisher.svg",
  },
];

export { termsAndCons, cebuData, serviceCardData, chooseUsCard };
